import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex flex-col antialiased  h-screen bg-[#F4F2EE] ">
          <header className="border-b border-gray-300 sticky top-0 bg-white z-50">
            <Header />
          </header>

          <main className="flex-1 w-6xl mx-auto ">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
